### ISSUE TITLE
Not really a transport

### ISSUE THREAD

**Issue by jsumners** [atis--/pino-spawn#1]
I wouldn't call this a transport in the way a transport is defined by the Pino [documentation](https://github.com/pinojs/pino/blob/master/docs/transports.md). This looks to be an in-process stream transformer. As a result, it may have implications on the performance of the host application.

@mcollina @davidmarkclements do you think we should promote a common term for a Pino based module implemented like this one?

**Comment by atis--** [comment]
Yes, you're right. It's not a pino transport. But I want something like this to let me keep the same configuration as for bunyan (without changing how the process is invoked in pm2 etc), and still let me send logs to various services based on their level (e.g., errors going to a slack channel).

The performance question matters though: does piping to a node child process like this versus doing it in shell (as suggested by pino docs) somehow hurt performance? I would love to find out,, and hopefully will get some time to profile it. Would be even better If you had an immediate answer to that :-) cause really I have no idea...

**Comment by jsumners** [comment]
Let's say you run this on a system with a dual core CPU. The immediate difference is that the way this module works, only one core gets used. With a traditional Pino transport, the second core gets used for "transporting" the logs. Which is to say, this module works within the same Node process as the application issuing the logs. Thus, it takes more time away from the application to process logging.

**Comment by atis--** [comment]
Wait, really? If I give data to a spawned child process, then I'd expect that child process to be able to run on a different core and work on that data independently?

Basically, why is there a difference between doing this:
`$ ./some_app | other_app`
vs.
(`some_app` spawns `other_app`, and then streams/pipes data to that spawned child)

**Comment by jsumners** [comment]
Sorry, I wasn't aware you are doing that; or I at least forgot about it in my reply. I'm not too sure about the details in that situation. Yes, the spawned process probably gets its own thread/core. But your spawning process does still have to keep track of it. So I don't know the implications there.

**Comment by davidmarkclements** [comment]
@atis-- I think this is a very interesting idea - if it is effectively the equivalent (which we're not certain of yet) this could be a *very* nice way to replicate the bunyan multitransport api but retaining the performance benefits of having transports in a separate process - it could effectively become a wrapper around any transport

would you be willing to add benchmarks?

 (see how we do benchmarks in pino repo)

we do need a different label for it other than transport - it's a "pino utility" at the least

**Comment by jsumners** [comment]
Hmmm, I may have to investigate that. It'd probably be better to use 'fork' instead of 'spawn' though. That spins up a completely new V8 process.

**Comment by atis--** [comment]
Node does not do the typical cheap fork(). It's always a completely separate process with its own memory and V8 instance. The difference is that [child_process.fork()](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) will create an additional IPC channel.

But yeah, let's investigate!

**Comment by mcollina** [comment]
I think this module is a transport runner. In some cases, doing `node app.js | transport` is complex to setup and just doing `node app.js`  has its benefits, however we want to keep handling logs into a separate process.

I think the best approach is to have it as a generic system that wraps any executable, rather than something specialized for each of the other transports. Something like `pino(pinoSpawn('grep matteo'))`. What do you think?

**Comment by jsumners** [comment]
I just wanted to bring this approach to you guys's attention. I didn't really want to try and convince @atis-- to rewrite his whole module.

Given the interest, I think an issue should be opened on a pinojs repo to address this topic. Which repo? `pino` or `community`?

**Comment by mcollina** [comment]
Yes, definitely. The generic cmd spawner is a really good idea!
